apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
  - name: welcome-http
    port: 7780
    targetPort: 80
    protocol: TCP